[package]
name = "bentoml-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bentoml_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.3"
